import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Form,
  Input,
  Select,
  Checkbox,
  Relevant,
  Debug,
  useFormApi,
} from "informed";

const Home: NextPage = () => {
  const formAPI = useFormApi();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form onSubmit={() => {}}>
          <Input name="name" label="Name" placeholder="Elon" />
          <Input name="age" type="number" label="Age" required="Age Required" />
          <Input name="phone" label="Phone" formatter="+1 (###)-###-####" />
          <Select name="car" label="Car" initialValue="ms">
            <option value="ms">Model S</option>
            <option value="m3">Model 3</option>
            <option value="mx">Model X</option>
            <option value="my">Model Y</option>
          </Select>
          <Checkbox name="married" label="Married?" />
          <Relevant when={({ formState }) => formState.values.married}>
            <Input name="spouse" label="Spouse" />
          </Relevant>
          <button type="submit">Submit</button>
          <Debug />
        </Form>
        <button
          onClick={() => {
            formAPI.setValue("email", "foo@bar.baz");
          }}
        >
          Set Email to foo@bar.baz
        </button>
      </main>
    </div>
  );
};

export default Home;
